name: "epl"

services:
  app:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
      args:
        src: ./epl_erratas
    image: epl-erratas:latest
    restart: always
    platform: linux/amd64
    environment:
      STREAMLIT_SERVER_PORT: 5432
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: false
      STREAMLIT_SERVER_FILE_WATCHER_TYPE: "none"
    command: [ "python", "-m", "streamlit", "run", "epl_erratas/app.py" ]
    ports:
      - ${EPL_ERRATAS_PORT:-5432}:5432
