services:
  app:
    build:
      args:
        dependencies: test
    image: epl-erratas:latest-dev
    user: "${UID_GID}"
    volumes:
      - ../:/app/src/
    environment:
      STREAMLIT_SERVER_FILE_WATCHER_TYPE: "auto"
