name: "epl"

services:
  app:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
      args:
        src: ./erratas
    image: epl-erratas:latest
    restart: always
    environment:
      STREAMLIT_SERVER_PORT: 5432
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: false
      DATA_PATH: /app/src/data
      STREAMLIT_SERVER_FILE_WATCHER_TYPE: "none"
    command: [ "python", "-m", "streamlit", "run", "erratas/app.py" ]
    ports:
      - ${EPL_ERRATAS_PORT:-5432}:5432